version: '3.9'
services: 
  db:
    image: postgres:13
    restart: always
    environment:
      POSTGRES_PASSWORD: toor 
    ports:
      - '5432:5432'
  spark:
    build: .
    volumes:
      - type: bind
        source: ./data
        target: /opt/data
    depends_on:
      - "db"
    environment:
      - SPARK_MODE=master
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
    ports:
      - '7077:7077'
      - '18080:8080'
  spark-worker-1:
    build: .
    volumes:
      - type: bind
        source: ./data
        target: /opt/data
    depends_on:
      - "spark"
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark:7077
      - SPARK_WORKER_MEMORY=6G
      - SPARK_WORKER_CORES=5
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
  etl:
    image: kotekaman/etlpostgres 
    volumes:
      - type: bind
        source: ./data
        target: /opt/data
    depends_on:
      - "spark"
      - "spark-worker-1"
      - "db"
    environment:
      POSTGRES_PASSWORD: toor
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432
      POSTGRES_USER: postgres
      SPARK_HOST: spark://spark:7077
      JAVA_HOME: /opt/bitnami/java